### ISSUE TITLE
[Question] Add Request and Response detail when updating testrail status

### ISSUE THREAD

**Issue by 4nif** [billylam/newman-reporter-testrail#8]
Hi @billylam,

* Is it possible to add request and response detail when updating testrail status for success and failed test result?
* Can we define other test status code other than failed and success?

thanks

**Comment by billylam** [comment]
Hi

1. It is possible to add logging, but how the reporter works is it batches all the results and makes a single call, not one for each test case so it would only log one thing.  Is that what you were looking for?
2. Currently no.  Are you looking to have failed cases be marked as "retest" or "blocked" instead of "failed"?  That should be possible to add.

**Comment by 4nif** [comment]
@billylam 

1. I would like to have request and response as comment when testrail plugin make an api call to update testrun status instead of test cases assertion result

2. Yes

**Comment by billylam** [comment]
Oh, thank you for clarifying.  I’ll try to make changes to add both when I have the time.

**Comment by billylam** [comment]
I've made the update.  Please try 1.0.10 and let me know if you see any issues.

**Comment by 4nif** [comment]
Thanks @billylam, I update to latest version 1.0.10 and here is my feedback

1. `pm.test.skip` looks good, now I can see plugin update test run status to `Not Implemented` 👍 
    ![image](https://user-images.githubusercontent.com/31293565/72317586-58d7fe00-36cc-11ea-9b8e-d3249a75e12f.png)


2. Request and response for **failed** test run still have some issue as follow:
    - Request url and other variable not resolved to environment variable value (e.g `{{service_endpoint}}`, `{{$guid}}`, etc)
    - Response body still undefined
![image](https://user-images.githubusercontent.com/31293565/72318047-c20c4100-36cd-11ea-920a-bec82e857a7a.png)

3. Request and response for **success* test still empty
![image](https://user-images.githubusercontent.com/31293565/72318389-b66d4a00-36ce-11ea-9ae6-558b02f3a556.png)

**Comment by billylam** [comment]
Unfortunately I noticed #2 as well but I don’t know if there’s a way to fix it.  In the object Newman provides me the variables weren’t resolved either.  I may have to see if they can make a change on their end.

For #3, the issue was that the API call to testrail doesn’t accept a comment, and fails if I try to add one initially.  But let me see if I can add it afterwards.

If I don’t fix #3 within a week feel free to reopen it.

**Comment by billylam** [comment]
Also for the undefined issue, I’ll look into hiding it when no response is given.  Unfortunately Newman doesn’t provide me a response code.

**Comment by billylam** [comment]
I've found a way to fix the first 2 based on what I see in other reporters, please bear with me for the wait while I figure out how to implement it.

**Comment by billylam** [comment]
I've made the changes, please try 1.0.12 and let me know if you're still seeing problems.

**Comment by 4nif** [comment]
Wow, it works. I can see (for failed and success test in Testrail)
* Request Header, 
* Request URL, 
* Request Body (if any)
* Request Response Code

I think the only thing are missing only the response header :D


Thank you very much @billylam 👍

**Comment by skoppudw** [comment]
hi there, 
How can I show request and response in the testrail run results? and how can I remove the header as the access token is a bearer its too big so testail not showing the results
